[versions]
kotlin = "1.8.10"

minecraft = "1.19.3"
qfapi = "5.0.0-beta.8+0.75.1-1.19.3"
qkl = "1.1.1+kt.1.8.10+flk.1.9.2"
loader = "0.18.6"
mappings = "1.19.3+build.28"
loom = "1.+"

yacl = "2.2.0"
modmenu = "5.1.0-beta.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
qfapi = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "qfapi" }
qfapi_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "qfapi" }

qkl = { module = "org.quiltmc.quilt-kotlin-libraries:quilt-kotlin-libraries", version.ref = "qkl" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "loader" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "mappings" }

yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[bundles]
quilted_fabric_api = ["qfapi", "qfapi_deprecated"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
quilt_loom = { id = "org.quiltmc.loom", version.ref = "loom" }
